/* Last Bus — a Canon adapter for a game that shares nothing with Vanity Shores.
 * Different globals, two stats instead of three, "tell" instead of "say", marks
 * instead of flags. If Canon needs editing to read this, it is not general. */
const path = require('path');

module.exports = {
  artifact: path.join(__dirname, 'toy.html'),
  out:      path.join(__dirname, 'toy-bible.html'),
  ready:    'window.TOY_READY === true',
  sceneMarker: /\btell\(/,
  statePattern: { source: 'STATE\\.marks\\.(NAME)' },
  axes: [
    { key:'build', re:/\bneed\(|STATS\.[a-z]+\s*>=/ },
    { key:'marks', re:/STATE\.marks\.[A-Za-z0-9_]+(?!\s*=[^=])/ },
    { key:'purse', re:/STATE\.coins\s*[<>=]/ }
  ],
  space: {
    stats: ['nerve','cash'], points: 60, min: 10, gate: 25,
    builds: { 'Even 30/30':[30,30], 'Nerve 45':[45,15], 'Cash 45':[15,45] },
    simulate: (D) => (b) => ({ passes: b.nerve >= D.CHECK || b.cash >= D.CHECK })
  },
  extract: () => ({ places: PLACES, folk: FOLK, prices: PRICES, CHECK }),

  render: (ctx, L) => L.page({
    title: 'Last Bus — Canon fixture',
    brand: ['Last Bus', 'Canon fixture'],
    nav: [['checks','Invariants'],['folk','Who is here'],['state','State']],
    body: `<h1>Last Bus</h1>
      <p class="sub">Generated by the same Canon that writes the Vanity Shores bible, from a game
      that shares no identifier with it. Everything below was read out of
      <code>toy.html</code> while it ran.</p>
      <section id="checks"><h2>Invariants</h2>
        <p class="lede">This fixture is <b>deliberately broken</b>. If these findings ever come back
        clean, Canon has stopped checking rather than the game having been fixed.</p>
        ${L.findings(ctx.findings)}</section>
      <section id="folk"><h2>Who is here</h2>
        ${L.table(['who','role','found'], [Object.values(ctx.data.folk).map(f =>
          `<tr><th>${L.esc(f.label)}</th><td>${L.esc(f.role)}</td><td>${L.esc(f.where)}</td></tr>`).join('')])}
      </section>
      <section id="state"><h2>State</h2>
        ${L.table(['mark','written','read','' ], [ctx.flags.map(f =>
          `<tr><th><code>${L.esc(f.name)}</code></th><td class="num">${f.writes}</td>
           <td class="num">${f.reads}</td><td>${L.esc(f.state)}</td></tr>`).join('')])}
      </section>`,
    foot: 'Fixture for <code>tools/canon-test.js</code>.'
  })
};
